### ISSUE TITLE
Cant delete content from  old vrsites account / beta.vsites account cant access content

### ISSUE THREAD

**Issue by hentosama** [vrsites/vrsites-public-issues#11]
So i have a few avatars on my old vrsites account, and now that i switched to beta.vrsites i have no way to access it (import?)

if i reupload all my assests get renamed because they are in the server already

if i could just delete everything from the old  vrsites so i can reupload fresh and new it would work wonders.

thanks

**Comment by sirkitree** [comment]
Hi @hentosama!

New files are uploaded to a new directory so they should not be renamed. However there is a known issue with Backdrop in which multiple file uploads to the same directory do get renamed rather than replaced, so this might be what you're running into.

Question: if you take one of your old assets, upload to the new beta, does it rename the file automatically? If so, can you give me more details about the filename and detailed steps in your process?

Thanks for using VR Sites!

**Comment by hentosama** [comment]
my old account was Hentosama on the vrsites

i made a new account hentosama on betavrsites and i found no way to see my files (it was a new account?)
then created a room and uploaded the same assets and they all got renamed from   name.ext  to   name_0.ext

i did create another account  bearpig, but i have not tried to upload the same files to that and see the result

cant you just enable file deltion on the old vrsites, so i can go in and delete my own stuff,  its all stuff i dont need and it probably fixes my issue.

i cant go renaming all the textures in blender and also match the  mtls for every single model i upload ;)

Date: Mon, 4 May 2015 06:40:12 -0700

**Comment by sirkitree** [comment]
@hentosama we've just released a new file browser that takes care of the _0 renaming problem. The account you created is new, we have not migrated older accounts over just yet, but that is almost complete as well.

**Comment by hentosama** [comment]
But then shoudl i delete m current account and wait for the old one to be carried over? 
will the old one be merged into the new?

if i could just delete my stuff at my old account on the old vr sites , it would take care of all my problems

i really havent  gone into janus and create content due to this, i know i coudl work on other models and such, but i had all set up hehe

Greetings and thanks for all!

Date: Wed, 3 Jun 2015 12:48:13 -0700

**Comment by sirkitree** [comment]
Keep your accounts as they are. The migration process should migrate your old rooms over to your new account as long as you registered with the same email address. 

Also, I think you'll find that the original problem you mentioned no longer exists, so feel free to create new rooms on beta.vrsites.com or re-create your old ones as you see fit. We're very close to having the migration working.

**Comment by hentosama** [comment]
thanks for your attention and work, i will try it out soon.
same email yeah ;)

Date: Mon, 8 Jun 2015 10:13:54 -0700
