### ISSUE TITLE
Suggestion for VR Sites server: Web page that lists active web pages and number of users on those pages

### ISSUE THREAD

**Issue by sirkitree** [vrsites/vrsites-public-issues#2]
>Note: I believe this is a server issue and not a Janus client problem. That's why I'm addressing VR Sites. /Note
All the other social VR programs (AltSpace, VR Chat, RiftMAX) have some sort of interface that allows users to see where other people are located. Not a fair criticism since the system the other programs use allow this more easily since they're not tracking users around the internet. Still, the ability to find other players has been requested now and again.
One solution is webpage that lists all the websites that people are transmitting as their current location. These are ranked based on how many players are in them. Being a webpage means that people can view it outside the game and decide if they would like to visit. No user names are listed. Since it's on the webpage, I can highlight links, copy, then paste in my TAB portal to quickly go there (until a more elegant method to do this gets made).
If there's ever a #channel system designed server side, this also allows a quick method to track how many people are in each channel and where players are currently congregating.

Ref: http://www.reddit.com/r/janusVR/comments/2sq0xf/suggestion_for_vr_sites_server_web_page_that/

**Comment by sirkitree** [comment]
This is a great suggestion and something I've actually been thinking about as well. The server currently logs some data about who connects and (I think) what urls they view, so with some better parsing of the logs or better logging in general we should be able to get this information.

My only concern is that then we're tracking people's browsing habits, which could be a major privacy concern. I think in order for us to do something like this we would need something in Janus that would allow users to opt in to this sort of tracking.

**Comment by sirkitree** [comment]
Re-reading this I see you make no mention of names, so that might be okay if we're simply reporting numbers of people currently inside of particular url. However, there is always the concern that we're listing someone in a room that they might not want to be known for frequenting. Case in point, I see that a particular url has one visitor and so I go there and now I know who is there and that individual feels like their privacy has been invaded.

Being social on the web is great, but I personally think we should try to maintain a privacy first policy.

Then again, they can always turn multiplayer off.

**Comment by Nukemarine** [comment]
I've had the same concerns when I considered this idea. It's a big reason James used hash coding instead of transmitting url's directly. A decent compromise is a two-fold presentation. First, display data from the last 10 (or 20 or 30 or more) minutes. Second, only display sites that have had at least 3 (5 or 7 or more) unique visitors in those tracked minutes. Both of these should help anonymity of those that visit "unique" webpages while still giving a decent idea on where groups might be congregating.

**Comment by sirkitree** [comment]
This has been implemented.
